# Generated by Django 3.0.4 on 2020-04-30 15:44

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200429_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/accounts/avatars/default_no_avatar.png', null=True, upload_to='accounts/avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username'), max_length=200, unique=True),
        ),
    ]
